### ISSUE TITLE
Can this architecture be realized using only linux servers, OVS & Quagga/FRR

### ISSUE THREAD

**Issue by bmullan** [CumulusNetworks/cldemo-evpn-centralized#6]
What I'm asking is there any dependencies that require physical routers & switches?

Instead of physical routers & switches could/can this be done using Linux OVS/Bridges and Quagga/FRR for routing to/from/across the Internet.

I tried looking thru the code for clues but since I'm not a Cumulus user or Ansible I easily could have glossed over the answer to my own question so thought I'd ask.

Thanks for any insight!
Brian

**Comment by plumbis** [comment]
This is based on Linux Bridge + FRR. Linux bridge provides the L2 component on the network while FRR provides the control plane for VxLAN. 

To the best of my knowledge, this would not work with OVS since there is no connection between OVS and FRR to dynamically build vxlan tunnels.

**Comment by bmullan** [comment]
Thanks Pete!  Okay linux bridges instead of OVS it is.

But the "solution" doesn't necessarily require physical routers & switches?

As an aside didn't you use to work at cisco I thought i recognized your name?

**Comment by plumbis** [comment]
Yes, you can do this on servers as well, we call it EVPN on the host. There are a few quirks around kernel version and the need for ifupdown2. I'd suggest joining the Cumulus Community slack to be able to ask some folks questions if you run into trouble. For example, I know that @packetninja has done this before and may have code to share. You can join at slack.cumulusnetworks.com 

And yes, I did work at Cisco for a number of years in the RTP TAC supporting routing. Small world :)
